version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --address :9002 --console-address :9003 /data
    ports:
      - "9002:9002"
      - "9003:9003"
    volumes:
      - ./data:/data  # Mount the host directory ./data to the container directory /data

  minio-init:
    image: minio/mc
    container_name: minio-init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin) do sleep 1; done;
      /usr/bin/mc mb myminio/nessie-bucket;
      exit 0;
      "

  nessie:
    image: projectnessie/nessie
    container_name: nessie
    ports:
      - "19120:19120"
    environment:
      - NESSIE_VERSION_STORE_TYPE=S3
      - NESSIE_VERSION_STORE_S3_ENDPOINT=http://minio:9000
      - NESSIE_VERSION_STORE_S3_ACCESS_KEY=minioadmin
      - NESSIE_VERSION_STORE_S3_SECRET_KEY=minioadmin
      - NESSIE_VERSION_STORE_S3_BUCKET=nessie-bucket
      - NESSIE_VERSION_STORE_S3_PATH_STYLE_ACCESS=true
    depends_on:
      - minio
      - minio-init

  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9001:9000"  # Change this to a different port, e.g., 9001:9000
      - "9009:9009"

#  spark:
#    image: bitnami/spark
#    container_name: spark
#    environment:
#      - SPARK_MODE=master
#    ports:
#      - "8088:8088"
#      - "7077:7077"
#      - "4040:4040"
