version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data
    ports:
      - "9000:9000"
      - "9001:9001"

  nessie:
    image: projectnessie/nessie
    container_name: nessie
    ports:
      - "19120:19120"

  nessie-ui:
    image: projectnessie/nessie-ui
    container_name: nessie-ui
    ports:
      - "8080:8080"
    environment:
      NESSIE_API_URL: http://nessie:19120/api/v1

  clickhouse:
    image: yandex/clickhouse-server
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"

  spark:
    image: bitnami/spark
    container_name: spark
    environment:
      - SPARK_MODE=master
    ports:
      - "8088:8088"
      - "7077:7077"
      - "4040:4040"
